[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[tool.ruff]

line-length = 80
indent-width = 4

[tool.ruff.lint]

select = ["D101", "E", "W", "F", "B", "Q", "I001", "NPY", "RUF"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.black]
line-length = 80

[tool.isort]
profile = "black"
